# Site settings
title: Tickator
email: info@tickator.org
description: > 
  This is Tickator. Oh.
baseurl: ""
url: "http://tickator.org"
twitter_username: tickator_org
github_username:  jkubos

# Build settings
markdown: kramdown
